version: "3.8"
services:
    elk:
        container_name: elk
        build: 
            context: ${PWD}/elk
            dockerfile: Dockerfile
        image: elk:latest
        ports:
            - "5044:5044"
            - "9200:9200"
            - "5601:5601"
        networks: 
            elastic:
                ipv4_address: 10.1.1.2
        volumes:
            - ${PWD}/elk/filebeat_logstash.conf:/etc/logstash/conf.d/filebeat_logstash.conf
    modsec:
        container_name: modsec
        build: 
            context: ${PWD}/modsec
            dockerfile: Dockerfile
        image: modsec:latest
        networks: 
            elastic:
                ipv4_address: 10.1.1.3
        ports:
            - "80:80"
            - "8000:8000"
            - "8080:8080"
            - "8888:8888"
        volumes: 
            - ${PWD}/modsec/Honeypot.conf:/usr/share/modsecurity-crs/rules/Honeypot.conf
            - ${PWD}/modsec/html/:/var/www/html/
        depends_on: 
            - elk
        privileged: true

volumes: 
    data-volume:

networks:
    elastic:
        driver: bridge
        ipam:
            config:
                - subnet: 10.1.1.0/24
                  gateway: 10.1.1.1
